import type {Metadata} from "next";
import {Geist} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers/providers";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{ children: React.ReactNode; }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
    <body
      className={`${geistSans.className} `}
    >
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Providers>
          {children}
        </Providers>
      </NextIntlClientProvider>
    </body>
    </html>
  );
}
