import type {Metadata} from "next";
import {Geist} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers/providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
    <body
      className={`${geistSans.className} `}
    >
      <Providers>
        {children}
      </Providers>
    </body>
    </html>
  );
}
