import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers/providers";
import { MessageSquare, Star } from "lucide-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <>
      <header className="bg-[#f0f0f0] shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <h1 className="text-4xl font-bold">
                <span className="text-[#0093d3]">S</span>
                <span className="text-green-500">o</span>
                <span className="text-yellow-500">m</span>
                <span className="text-red-500">o</span>
                <span className="text-green-500">n</span>
                <span className="text-gray-700">.tj</span>
              </h1>
              <span className="text-[12px] leading-3 font-semibold text-[#9da7b2] ml-2 w-37.5 ">Все объявления Таджикистана</span>
            </div>

            <div className="flex items-center space-x-4">
              <span className='text-[#0093d3] text-[15px]'>Имя</span>
              <span className="text-[#8391a2] text-[15px]">00 3305312</span>
              <button className="hover:bg-gray-100 rounded-full">
                <Star className="w-8 h-8 text-blue-500" />
              </button>
              <button className="hover:bg-gray-100 rounded-full">
                <MessageSquare className="w-8 h-8 text-blue-500" />
              </button>
              <button className="bg-[#ea4300] text-white px-3 py-1.5 rounded-sm hover:bg-orange-600 font-medium">
                Подать объявление
              </button>
              <div className="flex space-x-2">
                <button className="w-8 h-8 rounded overflow-hidden border-2 border-blue-500">
                  <img src="https://flagcdn.com/w40/ru.png" alt="RU" className="w-full h-full object-cover" />
                </button>
                <button className="w-8 h-8 rounded overflow-hidden border">
                  <img src="https://flagcdn.com/w40/tj.png" alt="TJ" className="w-full h-full object-cover" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </header>
      <html lang="en">
        <body
          className={`${geistSans.className} `}
        >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    </>
  );
}
